name: Bug Report
description: Report a bug regarding the library
title: "[BUG] "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for the report!
        Please fill out the details below.

  - type: input
    id: haxe-version
    attributes:
      label: Haxe version
      description: What version of Haxe are you using? (e.g. 4.3.4)
      placeholder: "4.3.x"
    validations:
      required: true

  - type: input
    id: library-version
    attributes:
      label: Library version
      description: Which version of this lib are you using?
      placeholder: "1.0.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and in a few words description of the problem.
      placeholder: "When I try to parse this, I get error Null"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1. Do 1+1
        2. Run 2+2
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen instead?
      placeholder: "It should return a Map, but it shows null."

  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Paste any error messages, or screenshots here.
      render: shell
