blank_issues_enabled: false
contact_links:
  - name: Start a Discussion
    url: https://github.com/anthonydudeh/hjson-haxe/discussions
    about: Ask questions, share ideas, or talk with the community.
